FROM python:3.9.19-slim-bullseye

# Create app directory
WORKDIR /app/src

# Copy the application code
COPY docker/requirements.txt /app/requirements.txt

# Install Python dependencies
RUN pip3 install --no-cache-dir -r /app/requirements.txt

COPY . /app/

# Run the application
CMD ["python", "app.py"]